code --install-extension icrawl.discord-vscode
code --install-extension kevinkyang.auto-comment-blocks 
code --install-extension aaron-bond.better-comments 
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension alefragnani.bookmarks
code --install-extension hookyqr.beautify
code --install-extension christian-kohler.path-intellisense
code --install-extension ionutvmi.path-autocomplete
code --install-extension mhutchie.git-graph
code --install-extension github.copilot
code --install-extension oderwat.indent-rainbow
code --install-extension naumovs.color-highlight
code --install-extension designbyajay.bash-cli-snippets
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension sumneko.lua
code --install-extension xabikos.javascriptsnippets
code --install-extension xabikos.ReactSnippets
code --install-extension pranaygp.vscode-css-peek
code --install-extension zignd.html-css-class-completion
code --install-extension ecmel.vscode-html-css
code --install-extension hwencc.html-tag-wrapper
code --install-extension bradlc.vscode-tailwindcss
code --install-extension mechatroner.rainbow-csv
code --install-extension pkief.material-icon-theme
code --install-extension whizkydee.material-palenight-theme
code --install-extension unthrottled.doki-theme
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension pawelgrzybek.gatito-theme
code --install-extension 2gua.rainbow-brackets
code --install-extension daylerees.rainglow
code --install-extension yandeu.five-server
code --install-extension redhat.vscode-yaml
code --install-extension redhat.vscode-xml