#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X XI

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/.wallpapers/anime/1.jpg
xsetroot -cursor_name left_ptr &
wmname LG3D &

bspc config focus_follows_pointer true
bspc config borgrder_width 0

picom --experimental-backends &

~/.config/polybar/shapes/preview.sh --shapes
~/.config/polybar/shapes/scripts/colors-dark.sh --gray

#Script cambio de color segun la hora del dia comentar la linea 29 para poder usar el script
#~/git/clone/zsh-with-plugins-and-more/config/polybar/polybar-themes/simple/shapes/scripts/colores.sh